# Generated by Django 5.2 on 2025-04-28 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='security_question',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
