# Generated by Django 5.1.7 on 2025-04-16 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_admin',
            new_name='is_staff',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_active',
        ),
    ]
