# Generated by Django 5.1.7 on 2025-04-16 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='expenses',
            new_name='expense',
        ),
    ]
