# Generated by Django 5.1.7 on 2025-04-20 12:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_rename_expenses_budget_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
