# Generated by Django 5.1.7 on 2025-04-21 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(),
        ),
    ]
